/**
 * HTML Template Generator
 * Handles the generation of complete HTML documents with CSS and JavaScript
 */

const { generateReportContent } = require('../generators/reportGenerator');
const { generateReportStyles } = require('./cssStyles');
const { generateReportScripts } = require('./jsScripts');

/**
 * Generate the complete HTML report with enhanced chart analysis
 * @param {Object} data - Report data
 * @param {string} reportType - Type of report
 * @returns {string} Complete HTML
 */
function generateReportHTML(data, reportType) {
  const cssStyles = require('./cssStyles');
  const jsScripts = require('./jsScripts');
  const reportGenerator = require('../generators/reportGenerator');

  // Generate the main report content
  const reportContent = reportGenerator.generateReportContent(data, reportType);

  return `
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Hacker News Validation Report - ${
      reportType.charAt(0).toUpperCase() + reportType.slice(1)
    }</title>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <style>
        ${cssStyles.generateReportStyles()}
    </style>
</head>
<body>
    <div class="container">
        ${reportContent}
        
        <div class="footer">
            <p>Generated by Please Hire Me - Hacker News Validation Tool</p>
            <p>Contact: <a href="mailto:jrbauti19@gmail.com">jrbauti19@gmail.com</a> | 
               <a href="https://www.linkedin.com/in/joshua-raphael-bautista-8a019a11b/" target="_blank">LinkedIn</a> | 
               <a href="https://www.joshuabautista.dev/" target="_blank">Portfolio</a></p>
        </div>
    </div>
    
    <script>
        ${jsScripts.generateReportScripts(data, reportType)}
    </script>
</body>
</html>
  `;
}

module.exports = {
  generateReportHTML,
};
